// examples/react/EnvAwareComponent.tsx
/**
 * React Component Example with @oxog/env-scout
 * Demonstrates environment-aware React components
 */

import React, { useEffect, useState } from 'react';
import {
  isMobile,
  isTablet,
  isDesktop,
  isDarkMode,
  isOnline,
  getEnvironmentInfo,
  isEnvironment,
  checkFeatureSupport,
  prefersReducedMotion,
  getScreenSize,
  type EnvironmentInfo
} from '@oxog/env-scout';

// Custom hook for environment detection
export function useEnvironment() {
  const [env, setEnv] = useState<EnvironmentInfo | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const envInfo = getEnvironmentInfo();
    setEnv(envInfo);
    setIsLoading(false);
  }, []);

  return { env, isLoading };
}

// Custom hook for responsive design
export function useResponsive() {
  const [viewport, setViewport] = useState({
    isMobile: isMobile(),
    isTablet: isTablet(),
    isDesktop: isDesktop(),
    screenSize: getScreenSize()
  });

  useEffect(() => {
    const handleResize = () => {
      setViewport({
        isMobile: isMobile(),
        isTablet: isTablet(),
        isDesktop: isDesktop(),
        screenSize: getScreenSize()
      });
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return viewport;
}

// Custom hook for user preferences
export function useUserPreferences() {
  const [preferences, setPreferences] = useState({
    darkMode: isDarkMode(),
    reducedMotion: prefersReducedMotion(),
    isOnline: isOnline()
  });

  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    const motionQuery = window.matchMedia('(prefers-reduced-motion: reduce)');

    const handleChange = () => {
      setPreferences({
        darkMode: isDarkMode(),
        reducedMotion: prefersReducedMotion(),
        isOnline: isOnline()
      });
    };

    mediaQuery.addEventListener('change', handleChange);
    motionQuery.addEventListener('change', handleChange);
    window.addEventListener('online', handleChange);
    window.addEventListener('offline', handleChange);

    return () => {
      mediaQuery.removeEventListener('change', handleChange);
      motionQuery.removeEventListener('change', handleChange);
      window.removeEventListener('online', handleChange);
      window.removeEventListener('offline', handleChange);
    };
  }, []);

  return preferences;
}

// Environment-aware component wrapper
interface EnvAwareProps {
  children: React.ReactNode;
  fallback?: React.ReactNode;
  conditions: string[];
}

export const EnvAware: React.FC<EnvAwareProps> = ({ 
  children, 
  fallback = null, 
  conditions 
}) => {
  const shouldRender = isEnvironment(conditions);
  return <>{shouldRender ? children : fallback}</>;
};

// Responsive image component
interface ResponsiveImageProps {
  src: string;
  alt: string;
  className?: string;
}

export const ResponsiveImage: React.FC<ResponsiveImageProps> = ({ 
  src, 
  alt, 
  className 
}) => {
  const getSrc = () => {
    const ext = src.split('.').pop();
    const baseName = src.replace(`.${ext}`, '');

    // Use WebP for supported browsers
    if (isEnvironment(['chrome']) || isEnvironment(['edge'])) {
      return `${baseName}.webp`;
    }

    // Use 2x for retina displays
    if (isEnvironment(['retina'])) {
      return `${baseName}@2x.${ext}`;
    }

    // Use compressed version for mobile
    if (isEnvironment(['mobile'])) {
      return `${baseName}-mobile.${ext}`;
    }

    return src;
  };

  return (
    <img 
      src={getSrc()} 
      alt={alt} 
      className={className}
      loading={isEnvironment(['mobile']) ? 'lazy' : 'eager'}
    />
  );
};

// Feature detection component
export const FeatureGate: React.FC<{
  features: string[];
  children: React.ReactNode;
  fallback?: React.ReactNode;
}> = ({ features, children, fallback }) => {
  const [supported, setSupported] = useState(false);

  useEffect(() => {
    const support = checkFeatureSupport(features);
    const allSupported = features.every(f => support[f]);
    setSupported(allSupported);
  }, [features]);

  return <>{supported ? children : fallback}</>;
};

// Main demo component
export const EnvironmentDashboard: React.FC = () => {
  const { env, isLoading } = useEnvironment();
  const viewport = useResponsive();
  const preferences = useUserPreferences();

  if (isLoading || !env) {
    return <div>Loading environment information...</div>;
  }

  return (
    <div className={`dashboard ${preferences.darkMode ? 'dark' : 'light'}`}>
      <h1>Environment Dashboard</h1>

      {/* Device-specific content */}
      <EnvAware conditions={['mobile']}>
        <div className="mobile-layout">
          <h2>Mobile Experience</h2>
          <p>Optimized for touch interaction</p>
        </div>
      </EnvAware>

      <EnvAware conditions={['desktop']}>
        <div className="desktop-layout">
          <h2>Desktop Experience</h2>
          <p>Full-featured interface with advanced controls</p>
        </div>
      </EnvAware>

      {/* Connection-aware content */}
      <EnvAware 
        conditions={['online']} 
        fallback={<div className="offline-message">You are currently offline</div>}
      >
        <div className="online-content">
          <h3>Connected</h3>
          <p>All features available</p>
        </div>
      </EnvAware>

      {/* Feature-based content */}
      <FeatureGate 
        features={['webgl2']} 
        fallback={<div>3D features not available</div>}
      >
        <div className="3d-content">
          <h3>3D Graphics Available</h3>
          <p>WebGL2 supported - enhanced graphics enabled!</p>
        </div>
      </FeatureGate>

      {/* Environment info display */}
      <div className="env-info">
        <h3>Current Environment</h3>
        <ul>
          <li>Runtime: {env.runtime}</li>
          <li>OS: {env.os}</li>
          <li>Browser: {env.browser?.name} {env.browser?.version}</li>
          <li>Device: {env.device.type}</li>
          <li>Screen: {viewport.screenSize?.width}x{viewport.screenSize?.height}</li>
          <li>Dark Mode: {preferences.darkMode ? 'Yes' : 'No'}</li>
          <li>Online: {preferences.isOnline ? 'Yes' : 'No'}</li>
        </ul>
      </div>

      {/* Responsive grid */}
      <div className={`grid ${viewport.isMobile ? 'mobile' : ''} ${viewport.isTablet ? 'tablet' : ''}`}>
        <div className="card">Card 1</div>
        <div className="card">Card 2</div>
        <div className="card">Card 3</div>
      </div>

      <style jsx>{`
        .dashboard {
          padding: 20px;
          font-family: system-ui, -apple-system, sans-serif;
        }

        .dark {
          background: #1a1a1a;
          color: #f0f0f0;
        }

        .light {
          background: #ffffff;
          color: #333333;
        }

        .grid {
          display: grid;
          gap: 20px;
          margin-top: 20px;
        }

        .grid.mobile {
          grid-template-columns: 1fr;
        }

        .grid.tablet {
          grid-template-columns: repeat(2, 1fr);
        }

        .grid:not(.mobile):not(.tablet) {
          grid-template-columns: repeat(3, 1fr);
        }

        .card {
          padding: 20px;
          background: rgba(0, 0, 0, 0.05);
          border-radius: 8px;
        }

        .dark .card {
          background: rgba(255, 255, 255, 0.05);
        }

        .offline-message {
          padding: 20px;
          background: #ffe6e6;
          border-radius: 8px;
          text-align: center;
        }

        .env-info ul {
          list-style: none;
          padding: 0;
        }

        .env-info li {
          padding: 5px 0;
        }
      `}</style>
    </div>
  );
};

// Example usage in App component
export default function App() {
  return (
    <div className="app">
      <EnvironmentDashboard />
    </div>
  );
}

// examples/vue/EnvAwareComponent.vue
<template>
  <div :class="['env-aware-app', { 'dark-mode': isDarkMode }]">
    <h1>Vue + @oxog/env-scout Example</h1>

    <!-- Loading state -->
    <div v-if="loading" class="loading">
      Loading environment information...
    </div>

    <!-- Main content -->
    <div v-else class="content">
      <!-- Device-specific rendering -->
      <div v-if="isMobile" class="mobile-view">
        <h2>Mobile View</h2>
        <p>Touch-optimized interface</p>
      </div>

      <div v-else-if="isTablet" class="tablet-view">
        <h2>Tablet View</h2>
        <p>Balanced layout for medium screens</p>
      </div>

      <div v-else class="desktop-view">
        <h2>Desktop View</h2>
        <p>Full-featured desktop interface</p>
      </div>

      <!-- Connection status -->
      <div class="connection-status" :class="{ offline: !isOnline }">
        <span v-if="isOnline">🟢 Online</span>
        <span v-else>🔴 Offline</span>
        <span v-if="connectionType"> - {{ connectionType }}</span>
      </div>

      <!-- Feature gates -->
      <div class="features">
        <h3>Available Features</h3>
        <div class="feature-grid">
          <div 
            v-for="(supported, feature) in features" 
            :key="feature"
            :class="['feature-card', { supported }]"
          >
            <span class="feature-name">{{ feature }}</span>
            <span class="feature-status">{{ supported ? '✓' : '✗' }}</span>
          </div>
        </div>
      </div>

      <!-- Environment details -->
      <div class="env-details">
        <h3>Environment Details</h3>
        <table>
          <tr>
            <td>Runtime:</td>
            <td>{{ envInfo.runtime }}</td>
          </tr>
          <tr>
            <td>OS:</td>
            <td>{{ envInfo.os }}</td>
          </tr>
          <tr>
            <td>Browser:</td>
            <td>{{ browserInfo }}</td>
          </tr>
          <tr>
            <td>Device Type:</td>
            <td>{{ envInfo.device.type }}</td>
          </tr>
          <tr>
            <td>Screen Size:</td>
            <td>{{ screenSize }}</td>
          </tr>
          <tr>
            <td>Orientation:</td>
            <td>{{ orientation }}</td>
          </tr>
          <tr>
            <td>Language:</td>
            <td>{{ envInfo.preferences.language }}</td>
          </tr>
          <tr>
            <td>Timezone:</td>
            <td>{{ envInfo.preferences.timezone }}</td>
          </tr>
        </table>
      </div>

      <!-- Adaptive components -->
      <div class="adaptive-section">
        <h3>Adaptive Components</h3>
        
        <!-- Responsive grid -->
        <div :class="gridClasses">
          <div v-for="i in 6" :key="i" class="grid-item">
            Item {{ i }}
          </div>
        </div>

        <!-- Performance mode indicator -->
        <div v-if="isSlowConnection" class="performance-warning">
          ⚠️ Slow connection detected - Performance mode enabled
        </div>
      </div>

      <!-- Actions -->
      <div class="actions">
        <button @click="refresh">Refresh Data</button>
        <button @click="toggleTheme">Toggle Theme</button>
        <button @click="showRawData = !showRawData">
          {{ showRawData ? 'Hide' : 'Show' }} Raw Data
        </button>
      </div>

      <!-- Raw data display -->
      <pre v-if="showRawData" class="raw-data">{{ JSON.stringify(envInfo, null, 2) }}</pre>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import {
  getEnvironmentInfo,
  isMobile,
  isTablet,
  isDesktop,
  isDarkMode as checkDarkMode,
  isOnline as checkOnline,
  getConnectionType,
  isSlowConnection as checkSlowConnection,
  checkFeatureSupport,
  getOrientation,
  isEnvironment,
  type EnvironmentInfo
} from '@oxog/env-scout';

// Reactive state
const loading = ref(true);
const envInfo = ref<EnvironmentInfo | null>(null);
const isDarkMode = ref(false);
const isOnline = ref(true);
const connectionType = ref<string | null>(null);
const isSlowConnection = ref(false);
const showRawData = ref(false);
const orientation = ref<string | null>(null);

// Device type checks
const isMobile = computed(() => envInfo.value?.device.type === 'mobile');
const isTablet = computed(() => envInfo.value?.device.type === 'tablet');
const isDesktop = computed(() => envInfo.value?.device.type === 'desktop');

// Features
const features = ref<Record<string, boolean>>({});

// Computed properties
const browserInfo = computed(() => {
  const browser = envInfo.value?.browser;
  return browser ? `${browser.name} ${browser.version}` : 'Unknown';
});

const screenSize = computed(() => {
  const screen = envInfo.value?.screen;
  return screen ? `${screen.width}x${screen.height}` : 'Unknown';
});

const gridClasses = computed(() => {
  return [
    'adaptive-grid',
    {
      'mobile-grid': isMobile.value,
      'tablet-grid': isTablet.value,
      'desktop-grid': isDesktop.value
    }
  ];
});

// Methods
const loadEnvironmentInfo = () => {
  envInfo.value = getEnvironmentInfo();
  isDarkMode.value = checkDarkMode();
  isOnline.value = checkOnline();
  connectionType.value = getConnectionType();
  isSlowConnection.value = checkSlowConnection();
  orientation.value = getOrientation();
  
  // Check features
  features.value = checkFeatureSupport([
    'webgl',
    'webgl2',
    'canvas',
    'webassembly',
    'serviceworker',
    'notification',
    'geolocation'
  ]);
  
  loading.value = false;
};

const refresh = () => {
  loading.value = true;
  setTimeout(loadEnvironmentInfo, 300);
};

const toggleTheme = () => {
  isDarkMode.value = !isDarkMode.value;
  // In a real app, you would also update the theme preference
};

// Event handlers
const handleResize = () => {
  if (envInfo.value) {
    envInfo.value = getEnvironmentInfo();
  }
};

const handleOnline = () => {
  isOnline.value = true;
  connectionType.value = getConnectionType();
};

const handleOffline = () => {
  isOnline.value = false;
  connectionType.value = null;
};

const handleOrientationChange = () => {
  orientation.value = getOrientation();
};

// Lifecycle
onMounted(() => {
  loadEnvironmentInfo();
  
  // Add event listeners
  window.addEventListener('resize', handleResize);
  window.addEventListener('online', handleOnline);
  window.addEventListener('offline', handleOffline);
  window.addEventListener('orientationchange', handleOrientationChange);
  
  // Media query listeners
  const darkModeQuery = window.matchMedia('(prefers-color-scheme: dark)');
  darkModeQuery.addEventListener('change', (e) => {
    isDarkMode.value = e.matches;
  });
});

onUnmounted(() => {
  // Clean up event listeners
  window.removeEventListener('resize', handleResize);
  window.removeEventListener('online', handleOnline);
  window.removeEventListener('offline', handleOffline);
  window.removeEventListener('orientationchange', handleOrientationChange);
});
</script>

<style scoped>
.env-aware-app {
  font-family: system-ui, -apple-system, sans-serif;
  padding: 20px;
  min-height: 100vh;
  transition: background-color 0.3s, color 0.3s;
}

.env-aware-app.dark-mode {
  background-color: #1a1a1a;
  color: #f0f0f0;
}

.loading {
  text-align: center;
  padding: 40px;
}

.content {
  max-width: 1200px;
  margin: 0 auto;
}

.connection-status {
  padding: 10px 20px;
  background: #d4edda;
  color: #155724;
  border-radius: 4px;
  display: inline-block;
  margin: 20px 0;
}

.connection-status.offline {
  background: #f8d7da;
  color: #721c24;
}

.features {
  margin: 30px 0;
}

.feature-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
  gap: 10px;
  margin-top: 10px;
}

.feature-card {
  padding: 15px;
  background: #f8f9fa;
  border-radius: 4px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.dark-mode .feature-card {
  background: #2d2d2d;
}

.feature-card.supported {
  border-left: 4px solid #28a745;
}

.feature-card:not(.supported) {
  border-left: 4px solid #dc3545;
}

.env-details table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 10px;
}

.env-details td {
  padding: 8px;
  border-bottom: 1px solid #e0e0e0;
}

.dark-mode .env-details td {
  border-bottom-color: #3d3d3d;
}

.env-details td:first-child {
  font-weight: 600;
  width: 150px;
}

.adaptive-grid {
  display: grid;
  gap: 15px;
  margin: 20px 0;
}

.mobile-grid {
  grid-template-columns: 1fr;
}

.tablet-grid {
  grid-template-columns: repeat(2, 1fr);
}

.desktop-grid {
  grid-template-columns: repeat(3, 1fr);
}

.grid-item {
  padding: 20px;
  background: #f0f0f0;
  border-radius: 4px;
  text-align: center;
}

.dark-mode .grid-item {
  background: #2d2d2d;
}

.performance-warning {
  padding: 15px;
  background: #fff3cd;
  color: #856404;
  border-radius: 4px;
  margin: 20px 0;
}

.actions {
  margin: 30px 0;
}

button {
  padding: 10px 20px;
  margin-right: 10px;
  background: #007bff;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.2s;
}

button:hover {
  background: #0056b3;
}

.raw-data {
  background: #f8f9fa;
  padding: 20px;
  border-radius: 4px;
  overflow-x: auto;
  font-size: 14px;
}

.dark-mode .raw-data {
  background: #2d2d2d;
}

/* Responsive adjustments */
@media (max-width: 768px) {
  .env-aware-app {
    padding: 10px;
  }
  
  .feature-grid {
    grid-template-columns: 1fr;
  }
  
  button {
    display: block;
    width: 100%;
    margin-bottom: 10px;
  }
}
</style>
